name: Docker Image CI and Release for aura Beta

on:
    workflow_dispatch:
    push:
        branches:
            - "master"
            - "beta*"
        paths:
            - "backend/**"
            - "frontend/**"
            - "VERSION.txt"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

            - name: Docker info
              run: docker info

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            - name: Log in to Docker Hub
              uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

            - name: Extract Version
              id: extract_version
              run: |
                  if [[ -f VERSION.txt ]]; then
                    APP_VERSION=$(cat VERSION.txt)
                    if [[ "${{ github.ref_name }}" == beta* ]]; then
                      APP_VERSION="${APP_VERSION}-beta"
                    fi
                    echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
                  else
                    echo "APP_VERSION=dev" >> $GITHUB_ENV
                  fi

            - name: Build Docker image
              run: |
                  docker buildx build . \
                    --platform linux/amd64,linux/arm64 \
                    --build-arg APP_VERSION=${{ env.APP_VERSION }} \
                    --tag ghcr.io/mediux-team/aura:beta \
                    --tag docker.io/mediux/aura:beta \
                    --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/aura:beta \
                    --tag ghcr.io/mediux-team/aura:${{ env.APP_VERSION }} \
                    --tag docker.io/mediux/aura:${{ env.APP_VERSION }} \
                    --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/aura:${{ env.APP_VERSION }} \
                    --push
