package argon2id

import (
	"errors"
	"testing"
)

// referenceHash was generated by github.com/alexedwards/argon2id v1.0.0
// (CreateHash with m=65536, t=1, p=2, 16-byte salt, 32-byte key) so this
// package stays verify-compatible with hashes created before the swap.
const referenceHash = "$argon2id$v=19$m=65536,t=1,p=2$zuv01LBGzAIB+IoOBvQCjg$8gE7bf/0c5idd9sPD5+MjJbz5uSgM0gdB/hQncEg/oQ"

const referencePassword = "correct horse battery staple"

func TestComparePasswordAndHash(t *testing.T) {
	match, err := ComparePasswordAndHash(referencePassword, referenceHash)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !match {
		t.Error("correct password must match a hash created by alexedwards/argon2id")
	}

	match, err = ComparePasswordAndHash("wrong password", referenceHash)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if match {
		t.Error("wrong password must not match")
	}
}

func TestDecodeHash(t *testing.T) {
	params, salt, key, err := DecodeHash(referenceHash)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if params.Memory != 65536 || params.Iterations != 1 || params.Parallelism != 2 {
		t.Errorf("params = %+v, want m=65536 t=1 p=2", params)
	}
	if len(salt) != 16 || params.SaltLength != 16 {
		t.Errorf("salt length = %d, want 16", len(salt))
	}
	if len(key) != 32 || params.KeyLength != 32 {
		t.Errorf("key length = %d, want 32", len(key))
	}
}

func TestDecodeHashErrors(t *testing.T) {
	cases := []struct {
		name string
		hash string
		want error
	}{
		{"not a PHC string", "plaintext", ErrInvalidHash},
		{"wrong variant", "$argon2i$v=19$m=65536,t=1,p=2$c29tZXNhbHQ$Zm9vYmFy", ErrIncompatibleVariant},
		{"wrong version", "$argon2id$v=18$m=65536,t=1,p=2$c29tZXNhbHQ$Zm9vYmFy", ErrIncompatibleVersion},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, _, _, err := DecodeHash(tc.hash); !errors.Is(err, tc.want) {
				t.Errorf("DecodeHash(%q) error = %v, want %v", tc.hash, err, tc.want)
			}
		})
	}
}
